### ISSUE TITLE
Exponential Grids for Tau and K

### ISSUE THREAD

**Issue by iintSjds** [kunyuan/QuantumStatistics.jl#22]

**Comment by kunyuan** [comment]
We hope the grids can do:
1) User-defined domains with the open/close boundary
2) Provide a coarse-grained grid which is exponential, and a fine grid that is uniform (later, we may consider generalize it to a quadrature grid that is non-uniform, package https://github.com/JuliaApproximation/FastGaussQuadrature.jl may be useful)
3) For each domain, the input parameters are the number of the coarse-grain grids, the number of the fine grid, and the smallest width of the bin.
4) for a given input x, there should be a fast floor function to return its closest coarse-grained grid point and another floor function to return the closest find grid point.  

A closely related issue is #3.

**Comment by kunyuan** [comment]
Two suggestions to consider:
1. Add a function that returns the indices of domain edges
2. Add a function that returns an optimized grid that satisfied a given accuracy for a given curve.
